### ISSUE TITLE
Unexpected "Requested a node find itself" error

### ISSUE THREAD

**Issue by ackintosh** [sigp/discv5#108]
I got the error when a response of FINDNODE contains ENR of the target node (the node passed to `Discv5::find_node()`).

## Error message

> 2022-04-14T01:11:36.349333Z ERROR discv5::service: Send RPC failed: Requested a node find itself

## Details of the case which occurs the issue

![20220414_requested_a_node_find_itself](https://user-images.githubusercontent.com/1885716/163581810-58b78c60-2323-4e3c-9578-0e293dfb7a56.png)

- (*1) https://github.com/sigp/discv5/blob/fdbb80432419578eebadf27c7d6fb098975f5de6/src/query_pool/peers/closest.rs#L180-L181
- (*2) https://github.com/sigp/discv5/blob/d47f7421f7d8a984cf0bceb1ec517310bb8dcf99/src/service/query_info.rs#L35-L36

## How to fix

I think we should skip to insert the peer into `closest_peers` if the peer received via NODES response and the target are same.

https://github.com/sigp/discv5/blob/fdbb80432419578eebadf27c7d6fb098975f5de6/src/query_pool/peers/closest.rs#L180-L181

I will file a PR to fix this issue. 😃

**Comment by ackintosh** [comment]
FYI: I've found out this issue while am implementing [this test plan](https://github.com/ackintosh/test-plan-discv5), a Testground test plan for discv5.

**Comment by AgeManning** [comment]
Sorry for the slow response on this. 

nice find! Thanks!
