### ISSUE TITLE
Speed up ENR update

### ISSUE THREAD

**Issue by AgeManning** [sigp/discv5#144]
We do pings every 5 minutes after connections for security reasons. 

I think its probably safe for us to ping outgoing connections that end up in our routing table on initial connection.

**Comment by divagant-martian** [comment]
can you be more specific when you say "on initial connection" ?

**Comment by AgeManning** [comment]
Yep. We initially had that when we established a connection (more specifically, create a new session) we would send a PING. This has security implications in that malicious users could start connections with us and try to game the IP voting mechanism.

Now, we only ping connections every ping-interval, and only connections in the routing table. Although this is safer, the downside is that we don't start receiving PONG responses until after the ping-interval on start-up. This can be a decent amount of time.

Perhaps a middle ground is that new connections that are outgoing and make it into the routing table, we send PING's to when they first enter the table. This would allow us to start getting PONG responses early in order to update our ENR faster (when measuring time from start-up)
