### ISSUE TITLE
Examples on MacOS

### ISSUE THREAD

**Issue by arsenron** [sigp/discv5#170]
Hi! I tried to run `find_nodes` example on MacOS to setup two "nodes" on localhost and it was a little bit unclear how to setup this. On Linux everything worked fine.

The problem is that by default `SocketKind` is dual stack (ip4 + ip6), so I supposed it should work when I bind to "ip6 socket" , which is by default, and try to send packets to the "ip4 socket". But I failed it to work and was getting an IO error: `Error: Os { code: 22, kind: InvalidInput, message: "Invalid argument" }`. The solution is to bind to the ip4 socket, but the error itself is very unclear and maybe it should be addressed to tokio itself, but could we make it more clear in the example documentation for MacOS? Or find some other ways like adding conditional compilation and require to specify `SocketKind` when `#[cfg(target_os = "macos")]`?

**Comment by divagant-martian** [comment]
Hi, thanks for giving it a try on mac. If you gives us the commands you are using to setup the two nodes we can better look into it

**Comment by ackintosh** [comment]
I confirmed that the error has been reproduced with the commands:

```bash
# Node1
cargo run --example find_nodes -- \
  --enr-ip4 127.0.0.1 \
  --port 9000
```


```bash
# Node2
RUST_LOG=trace cargo run --example find_nodes -- \
  --enr-ip4 127.0.0.1 \
  --port 9001 \
  --remote-peer=(Node1 ENR)
```

Then the log below occurs in Node2.

```
2023-04-26T22:47:59.930963Z TRACE discv5::socket::send: Could not send packet. Error: Os { code: 22, kind: InvalidInput, message: "Invalid argument" }
```

---

Also I confirmed that this issue doesn't occur on the [two-sockets](https://github.com/sigp/discv5/pull/160) branch we are working on.

**Comment by AgeManning** [comment]
Oh nice. So I guess its an issue with the socket library we are using?

**Comment by divagant-martian** [comment]
Hey @arsenron  could you give this a try again using master? You can run `cargo run --example find_nodes -- --help` to guide you

**Comment by arsenron** [comment]
@divagant-martian Everything now works, thanks!
