### ISSUE TITLE
Add CI to prevent none used depends from being added not detected

### ISSUE THREAD

**Issue by KolbyML** [sigp/discv5#177]
In this PR https://github.com/sigp/discv5/pull/176 2 dependencies were added which aren't used. We should probably have a CI test to detect this. I am not sure if that is possible but I will look into it. This tastes like something a CI should detect

**Comment by divagant-martian** [comment]
we can add udeps. I'll do that

**Comment by KolbyML** [comment]
I already did it

**Comment by KolbyML** [comment]
so sad
