### ISSUE TITLE
Add Error Metric

### ISSUE THREAD

**Issue by AgeManning** [sigp/discv5#213]
It would be useful to add a warning and error metric to the global metrics. 

This way if an error or warning occurs we increment these counts. Often in Lighthouse, we dont emit logs for discovery and a variety of errors and warnings can go unnoticed. 

If we had these in the metrics we could just monitor metrics for discovery to observe if anything is going wrong. 
I think it would be good to add the following metrics:
- Error count
- Warning count
- Error Type - Give some string context as to which type of error this is. As the debug logs are not saved and we see a large error/warning count it would be good to provide some context into what these errors are.

**Comment by jmcph4** [comment]
> Error Type - Give some string context as to which type of error this is. As the debug logs are not saved and we see a large error/warning count it would be good to provide some context into what these errors are.

Is the intent here for this to collect the actual error types themselves (i.e., `Vec<ErrorKind>`) or maintain counters for each type?

**Comment by AgeManning** [comment]
Upstream users can build their own as was done in lighthouse.
