### ISSUE TITLE
Handling zero port number on ip vote

### ISSUE THREAD

**Issue by ackintosh** [sigp/discv5#217]
On ip vote, port number should be non-zero since the number comes from external address that respond as PONG response by peers.

go-ethereum handles that as adopting a voting result (port number) only if the port number is non-zero.
https://github.com/ethereum/go-ethereum/blob/master/p2p/enode/localnode.go#L251-L255

It would be good to have a similar handling in our discv5 implemenation.

**Comment by ackintosh** [comment]
Changing `port` of [ReponseBody::Pong](https://github.com/sigp/discv5/blob/master/src/rpc.rs#L91-L92) from `u16` to `NonZeroU16` seems make sense to eliminate the case that voting result is zero port number.

How do you think?

**Comment by divagant-martian** [comment]
yeah agree, let's do it!
