### ISSUE TITLE
move discv5 to structured logging

### ISSUE THREAD

**Issue by divagant-martian** [sigp/discv5#222]
transform logging statements from using formating in strings to structured logging, for example:
```diff
- debug!("Node set to disconnected: {}", node_id)
+ debug!(%node_id, "Node set to disconnected")
```
This would make it easier to make sense of emitted logs

**Comment by emhane** [comment]
it should be possible to shorten lists of node ids with 
```rust
format!("[{:#}]", list.iter().format(", "))
```
https://github.com/paradigmxyz/reth/issues/6080#issuecomment-1893329173
