### ISSUE TITLE
crates.io release

### ISSUE THREAD

**Issue by DaniPopes** [sigp/discv5#244]
Hello, is it possible to release with the updated `enr` dependency?
This would unblock bumping a few other dependencies in reth:
- https://github.com/paradigmxyz/reth/pull/7000

Thanks!

**Comment by AgeManning** [comment]
Hey, yep!.  

Was hoping to get this guy in quickly as a minor release to ENR, then release discv5 with that fix: https://github.com/sigp/enr/pull/70

**Comment by AgeManning** [comment]
Apologies for the delay. v0.5.0 is released.
