### ISSUE TITLE
reduce libp2p dependencies

### ISSUE THREAD

**Issue by mattsse** [sigp/discv5#253]
the libp2p feature pulls in libp2p entirely:

https://github.com/sigp/discv5/blob/44051ef77146003adb100cf87952da42a68e4174/Cargo.toml#L17-L17

but only identity and MultiAddr are used

https://github.com/sigp/discv5/blob/44051ef77146003adb100cf87952da42a68e4174/src/node_info.rs#L7-L11

which are available as standalone crates:

`multiaddr` and `libp2p-identity`

**Comment by AgeManning** [comment]
Resolved in #255
