### ISSUE TITLE
The limit of packet size

### ISSUE THREAD

**Issue by ackintosh** [sigp/discv5#47]
From [the wire protocol](https://github.com/ethereum/devp2p/blob/master/discv5/discv5-wire.md#udp-communication), there's a limited range of packet size which implementations should consider the packet is valid:

- the maximum size of any packet is 1280 bytes
- the minimum size of any packet is 63 bytes

Currently we support the limit [partially](https://github.com/sigp/discv5/blob/f117b3ca56fa3dca2317270434634ff7106d391a/src/socket/recv.rs#L17), not sufficient. I'll file a PR to improve that. 😃

**Comment by ackintosh** [comment]
Ah, I just realized that handling for the minimum size  is implemented already. 😃 💦 

https://github.com/sigp/discv5/blob/0ace2b64e9464278d37b0ecb50d58090c59ff50b/src/packet/mod.rs#L407-L411

**Comment by AgeManning** [comment]
I think we handle both these cases already. 

You've found the minimum size one. The maximum is handled by the `recv_from` function of the udp socket: 
https://github.com/sigp/discv5/blob/master/src/socket/recv.rs#L91

If any packet is sent larger than the maximum, the excess bytes are discarded and the packet will likely fail decoding. 

It is therefore impossible to get a packet larger than 1280 bytes in the decode function.
