### ISSUE TITLE
Re-implement lru-time-cache

### ISSUE THREAD

**Issue by AgeManning** [sigp/discv5#71]
The current `lru_time_cache` dependency is in efficient under most operations.

We are using this cache for a variety of fields in the handler. The sessions in particular can be quite large and we don't want to be doing O(n) operations on every get for every message.

See eg, https://github.com/maidsafe/lru_time_cache/issues/143

**Comment by ackintosh** [comment]
I'm working on this issue, will file a PR in a few days. 😃
