### ISSUE TITLE
Expose PING and FINDNODE rpc to public API

### ISSUE THREAD

**Issue by ogenev** [sigp/discv5#90]
We at [Trin](https://github.com/ethereum/trin) would benefit greatly if we have public API access to raw `PING` and `FINDNODE` RPC via Discv5 pub struct.  For example, something like `send_ping(enr: Enr)` and `send_findnode(enr: Enr, distances: Vec<u64>)` would be great.

Are you guys open to such a change? If you agree, we can discuss the implementation approach and I can work on a PR to commit this upstream?

**Comment by ogenev** [comment]
Thanks for the discussion, it is really helpful! 

It seems our use cases are not very clear right now. The next milestone for Portal Network is running a test network on top of discv5 protocol and our assumption is that we may need to send raw PING and FINDNODE base layer discv5 RPCs mainly for testing and development purposes. 

Maybe we should wait and see if we will really need those raw base layer RPCs and then look for a way to implement them.

**Comment by AgeManning** [comment]
Sure. It sounds to me like if you need them in conjunction with all the DHT logic and everything provided in the service, then we can add it, but we should do it via a compile-time feature flag, such that they are not exposed to regular users.

Let's re-open this when you need.
